# https://taskfile.dev
version: '3'

vars:
  HOSTNAME:
    sh: "hostname -s"
  USERNAME:
    sh: "whoami"
tasks:
  update:
    cmds:
      - nix flake update
  apply:
    cmds:
      - nix run home-manager -- switch --flake '.#{{.USERNAME}}@{{.HOSTNAME}}'
  apply_darwin:
    status:
      - "test $(uname -s) -ne Darwin"
    cmds:
      - nix build './#darwinConfigurations.{{ .HOSTNAME }}.system'
      - ./result/sw/bin/darwin-rebuild switch --flake .
  clean:
    cmds:
      - nix-collect-garbage -d

  apply_mibzy:
    cmds:
      - nix run nixpkgs#nixos-rebuild -- switch --fast --flake .#mibzy --target-host admin@mibzy --build-host admin@mibzy --use-remote-sudo

  anywhere-mibzy:
    cmds:
      - nix run github:nix-community/nixos-anywhere -- --flake .#mibzy --target-host root@{{TODO}} --build-on-remote --extra-files ./.secrets/mibzy/ --disk-encryption-keys /tmp/secret.key <(cat ./.secrets/mibzy_encryption)
