# See https://wiki.hypr.land/Configuring/Basics/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# ASUS PA329CV 32" 4K
env = GDK_SCALE,1.75
monitor = desc:ASUSTek COMPUTER INC ASUS PA329CV T2LMTF032874, 3840x2160@60, auto, 1.6

# Internal laptop display
monitor = desc:BOE NE135A1M-NY1, 2880x1920@120, auto, 2

# Fallback for any other monitors
monitor = , preferred, auto, auto
