after-login-command = []
after-startup-command = []
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# alt-shift-h = 'move left'
# alt-shift-j = 'move down'
# alt-shift-k = 'move up'
# alt-shift-l = 'move right'

# alt-shift-1 = 'workspace 1'
# alt-shift-2 = 'workspace 2'
# alt-shift-3 = 'workspace 3'
# alt-shift-4 = 'workspace 4'
# alt-shift-5 = 'workspace 5'
# alt-shift-6 = 'workspace 6'
# alt-shift-7 = 'workspace 7'
# alt-shift-8 = 'workspace 8'
# alt-shift-9 = 'workspace 9'
# alt-shift-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
# alt-shift-b = 'workspace B'
# alt-shift-c = 'workspace C'
# alt-shift-d = 'workspace D'
# alt-shift-e = 'workspace E'
# alt-shift-f = 'workspace F'
# alt-shift-g = 'workspace G'
# alt-shift-i = 'workspace I'
# alt-shift-m = 'workspace M'
# alt-shift-n = 'workspace N'
# alt-shift-o = 'workspace O'
# alt-shift-p = 'workspace P'
# alt-shift-q = 'workspace Q'
# alt-shift-r = 'workspace R'
# alt-shift-s = 'workspace S'
# alt-shift-t = 'workspace T'
# alt-shift-u = 'workspace U'
# alt-shift-v = 'workspace V'
# alt-shift-w = 'workspace W'
# alt-shift-x = 'workspace X'
# alt-shift-y = 'workspace Y'
# alt-shift-z = 'workspace Z'
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace A'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace W'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace O'

[[on-window-detected]]
if.app-id = 'com.firstversionist.polypane'
run = 'move-node-to-workspace P'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace Z'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace Z'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'com.culturedcode.ThingsMac'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace F'

[[on-window-detected]]
if.app-id = 'com.usebruno.app'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus'
run = 'move-node-to-workspace 9'
